name: "Version and Release"
on:
    push:
        tags:
            - "v*"
jobs:
    get_branch:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - run: |
                echo ${{ github.ref }}
                echo ${{ github.head_ref }}
            - name: Git info
              id: git_branch
              run: |
                raw=$(git branch -r --contains ${{ github.ref }})
                branch=${raw##*/}
                echo "{name}=branch" >> $GITHUB_OUTPUT
                echo "Branch is $branch."